language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8
  - 7.10
  - 8.4.1
install:
  - ghc-pkg list --global
  - ghc-pkg list --user
  - cabal install QuickCheck
  - cabal install --only-dependencies
  - ghc-pkg list --global
  - ghc-pkg list --user
